### ISSUE TITLE
Web page not displaying games.

### ISSUE THREAD

**Issue by Dozer316** [Mako88/dxx-tracker#31]
Hi there -  pulled the repo from git and the server.php instanced is running fine and logging games from hosting clients - other clients can see the games in the ingame browser when pointed at my local tracker.

The web page loads fine, shows that the backend process is running fine but never retrieves a list of games from the sqlite database.  If I run games.php manually there is no ouput either.

I noticed that the web page on the main tracker at http://dxxtracker.hopto.org/ also didn't show any game output when I pointed my client there and hosted a game.

Thanks in advance.

**Comment by Mako88** [comment]
http://tracker.dxx-rebirth.com is now up and running. Let me know if you still have issues with it!
