### ISSUE TITLE
Tracker registers D1X games but not D2X

### ISSUE THREAD

**Issue by megamangk** [Mako88/dxx-tracker#33]
Screen shots are attached with packet captures showing bidirectional UDP traffic with tracker IP. UDP stream contents shown. Tracker seems to only register D1X even when selecting all.

![D1X listed](https://user-images.githubusercontent.com/58087380/69452385-86897200-0d2f-11ea-948d-f17a20456c85.PNG)
![D1X working pcap](https://user-images.githubusercontent.com/58087380/69452389-88ebcc00-0d2f-11ea-8bb4-612b96056a09.PNG)
![D2X not listed](https://user-images.githubusercontent.com/58087380/69452392-8a1cf900-0d2f-11ea-8d77-97e76114e4d6.PNG)
![D2X not working pcap](https://user-images.githubusercontent.com/58087380/69452394-8b4e2600-0d2f-11ea-96a9-bf3b9097fde9.PNG)

**Comment by Mako88** [comment]
This is now fixed
